name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:

env:
  php_extensions: curl,json
  default_php: 8.1

jobs:
  cs-check:
    name: CS Checks
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.default_php }}
          extensions: ${{ env.php_extensions }}
          tools: cs2pr

      - uses: "ramsey/composer-install@2.1.0"

      - name: "Check CS"
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr

  psalm:
    name: Psalm Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - run: cp config.dist.php config.php

      - name: "Setup PHP"
        if: hashFiles('psalm.xml') != ''
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.default_php }}
          extensions: ${{ env.php_extensions }}
          tools: cs2pr

      - uses: "ramsey/composer-install@2.1.0"
        if: hashFiles('psalm.xml') != ''

      - name: "Psalm"
        if: hashFiles('psalm.xml') != ''
        run: vendor/bin/psalm --output-format=github

  run-tests:

    name: PHPUnit on ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']
        include:
          - php-version: '8.2'
            composer-options: "--ignore-platform-reqs"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.php_extensions }}
          coverage: pcov
          ini-values: pcov.enabled=1

      - uses: "ramsey/composer-install@2.1.0"
        with:
          composer-options: "${{ matrix.composer-options }}"

      - name: "Run Tests"
        run: echo "Wot no tests?"
